# Nombre de la aplicaci�n y puerto
spring.application.name=ms-stock
server.port=8083

# DataSource (MySQL en XAMPP)
spring.datasource.url=jdbc:mysql://localhost:3306/ms_stock
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Configuraci�n de cat�logo (usar el mock PHP)
app.catalogo.url=http://localhost
app.catalogo.timeout=5
app.catalogo.endpoint.producto-por-id=/catalogo/producto.php?id={id}

# Si no usas Eureka, puedes deshabilitarlo
spring.cloud.discovery.enabled=false

# Logging
logging.level.root=INFO
logging.level.cl.dsy1103.ms_stock=DEBUG